// @generated by schema-rust from an authority-verified bootstrap source
// source-digest: blake3:91757dae67e9e52d1553c56731c91a018794cd3b69f0378e0143e320d10a6628

pub struct ObserveHead(Unit);

pub struct Configure(ConfigureRequest);

pub struct ObserveHeadObject(Unit);

pub struct Import(ImportRequest);

pub struct Configured(ConfigureReceipt);

pub struct HeadObserved(VersionedLogHead);

pub struct HeadObjectObserved(VersionedLogHeadObject);

pub struct Rejected(ConfigureRejection);

pub struct Imported(ImportReceipt);

pub struct CriomeSocketPath(CriomeSocketPathText);

pub struct VersionedLogHeadObject(signal_spirit::DatabaseMarker, SelectedHeadObject);

pub enum ArchiveDatabaseTarget {
    Path(ArchivePath),
    Default,
}

pub struct HeadDigestHex(String);

pub struct MirrorAddressText(String);

pub struct ConfigureRequest(ArchiveDatabaseTarget, SelectedMirrorTarget, SelectedCriomeGateTarget, SelectedGuardianPromptTarget);

pub struct SelectedMirrorTarget(Option<MirrorTarget>);

pub enum CriomeGateTarget {
    Default,
    Socket(CriomeSocketPath),
}

pub struct SelectedHeadObject(Option<HeadObjectHex>);

pub struct SelectedHeadDigest(Option<HeadDigestHex>);

pub struct ArchivePathText(String);

pub struct HeadObjectHex(String);

pub enum GuardianPromptTarget {
    Prompt(GuardianPrompt),
    Default,
}

pub struct ImportedRecords(Vec<ImportedRecord>);

pub struct GuardianPrompt(GuardianPromptText);

pub struct ImportedRecord(signal_spirit::RecordIdentifier, signal_spirit::Entry);

pub struct ConfigureReceipt(ArchiveDatabaseTarget, SelectedMirrorTarget, SelectedCriomeGateTarget, SelectedGuardianPromptTarget, signal_spirit::DatabaseMarker);

pub enum ConfigureRejectionReason {
    ArchiveTargetUnwritable,
    InternalError,
}

pub enum MirrorTarget {
    Address(MirrorAddress),
    Default,
}

pub struct SelectedCriomeGateTarget(Option<CriomeGateTarget>);

pub struct VersionedLogHead(signal_spirit::DatabaseMarker, SelectedHeadDigest);

pub struct GuardianPromptText(String);

pub struct ImportRequest(ImportedRecords);

pub struct SelectedGuardianPromptTarget(Option<GuardianPromptTarget>);

pub struct ConfigureRejection(ConfigureRejectionReason, signal_spirit::DatabaseMarker);

pub struct CriomeSocketPathText(String);

pub struct ImportReceipt(signal_spirit::RecordCount, signal_spirit::DatabaseMarker);

pub struct ArchivePath(ArchivePathText);

pub struct MirrorAddress(MirrorAddressText);

impl protos::Output for Configured {

}

impl protos::Output for HeadObserved {

}

impl protos::Output for HeadObjectObserved {

}

impl protos::Output for Rejected {

}

impl protos::Output for Imported {

}

impl protos::Input for ObserveHead {

}

impl protos::Input for Configure {

}

impl protos::Input for ObserveHeadObject {

}

impl protos::Input for Import {

}