//! Schema-derived MetaSignal contract for privileged `spirit` policy.
//!
//! `schema/meta-signal.schema` is the source of truth. The checked-in file
//! under `src/schema/` is generated by `schema-rust` as a wire contract.
//! Runtime actors, sockets, storage, guardian calls, and daemon lowering live
//! in `spirit`.

#![forbid(unsafe_code)]

#[rustfmt::skip]
pub mod schema;

pub use schema::meta_signal::*;

pub type MetaRequest = Input;
pub type MetaReply = Output;

pub const META_SIGNAL_SCHEMA_SOURCE: &str = include_str!("../schema/meta-signal.schema");
pub const META_SIGNAL_RUST_SOURCE: &str = include_str!("schema/meta_signal.rs");

impl ConfigureRequest {
    pub fn new(
        archive_database_target: ArchiveDatabaseTarget,
        mirror_target: Option<MirrorTarget>,
        criome_gate_target: Option<CriomeGateTarget>,
    ) -> Self {
        Self {
            archive_database_target,
            selected_mirror_target: SelectedMirrorTarget::new(mirror_target),
            selected_criome_gate_target: SelectedCriomeGateTarget::new(criome_gate_target),
        }
    }

    pub fn mirror_target(&self) -> Option<&MirrorTarget> {
        self.selected_mirror_target.payload().as_ref()
    }

    pub fn criome_gate_target(&self) -> Option<&CriomeGateTarget> {
        self.selected_criome_gate_target.payload().as_ref()
    }
}

impl ConfigureReceipt {
    pub fn new(
        archive_database_target: ArchiveDatabaseTarget,
        mirror_target: Option<MirrorTarget>,
        criome_gate_target: Option<CriomeGateTarget>,
        database_marker: signal_spirit::DatabaseMarker,
    ) -> Self {
        Self {
            archive_database_target,
            selected_mirror_target: SelectedMirrorTarget::new(mirror_target),
            selected_criome_gate_target: SelectedCriomeGateTarget::new(criome_gate_target),
            database_marker,
        }
    }

    pub fn mirror_target(&self) -> Option<&MirrorTarget> {
        self.selected_mirror_target.payload().as_ref()
    }

    pub fn criome_gate_target(&self) -> Option<&CriomeGateTarget> {
        self.selected_criome_gate_target.payload().as_ref()
    }
}
