// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_spirit::schema::signal::DatabaseMarker as DatabaseMarker;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::Entry as Entry;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::RecordIdentifier as RecordIdentifier;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::RecordCount as RecordCount;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::RemovalCandidateCollection as RemovalCandidateCollection;
#[rustfmt::skip]
pub use signal_spirit::schema::signal::RemovalCandidatesCollection as RemovalCandidatesCollection;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ArchivePathText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ArchivePath(ArchivePathText);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ArchiveDatabaseTarget {
    Default,
    Path(ArchivePath),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MirrorAddressText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MirrorAddress(MirrorAddressText);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MirrorTarget {
    Default,
    Address(MirrorAddress),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CriomeSocketPathText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CriomeSocketPath(CriomeSocketPathText);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CriomeGateTarget {
    Default,
    Socket(CriomeSocketPath),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GuardianPromptText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GuardianPrompt(GuardianPromptText);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum GuardianPromptTarget {
    Default,
    Prompt(GuardianPrompt),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SelectedMirrorTarget(Option<MirrorTarget>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SelectedCriomeGateTarget(Option<CriomeGateTarget>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SelectedGuardianPromptTarget(Option<GuardianPromptTarget>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ConfigureRequest {
    pub archive_database_target: ArchiveDatabaseTarget,
    pub selected_mirror_target: SelectedMirrorTarget,
    pub selected_criome_gate_target: SelectedCriomeGateTarget,
    pub selected_guardian_prompt_target: SelectedGuardianPromptTarget,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ConfigureReceipt {
    pub archive_database_target: ArchiveDatabaseTarget,
    pub selected_mirror_target: SelectedMirrorTarget,
    pub selected_criome_gate_target: SelectedCriomeGateTarget,
    pub selected_guardian_prompt_target: SelectedGuardianPromptTarget,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ConfigureRejection {
    pub configure_rejection_reason: ConfigureRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ConfigureRejectionReason {
    ArchiveTargetUnwritable,
    InternalError,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ImportedRecord {
    pub record_identifier: RecordIdentifier,
    pub entry: Entry,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ImportedRecords(Vec<ImportedRecord>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ImportRequest(ImportedRecords);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ImportReceipt {
    pub record_count: RecordCount,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CollectRemovalCandidatesRequest(RemovalCandidateCollection);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RemovalCandidatesCollectedReceipt {
    pub removal_candidates_collection: RemovalCandidatesCollection,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HeadDigestHex(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SelectedHeadDigest(Option<HeadDigestHex>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct VersionedLogHead {
    pub database_marker: DatabaseMarker,
    pub selected_head_digest: SelectedHeadDigest,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HeadObjectHex(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SelectedHeadObject(Option<HeadObjectHex>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct VersionedLogHeadObject {
    pub database_marker: DatabaseMarker,
    pub selected_head_object: SelectedHeadObject,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Configure(ConfigureRequest),
    Import(ImportRequest),
    CollectRemovalCandidates(CollectRemovalCandidatesRequest),
    ObserveHead,
    ObserveHeadObject,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Configured(ConfigureReceipt),
    Imported(ImportReceipt),
    RemovalCandidatesCollected(RemovalCandidatesCollectedReceipt),
    Rejected(ConfigureRejection),
    HeadObserved(VersionedLogHead),
    HeadObjectObserved(VersionedLogHeadObject),
}

#[rustfmt::skip]
impl ArchivePathText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ArchivePathText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ArchivePath {
    pub fn new(payload: ArchivePathText) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ArchivePathText {
        &self.0
    }
    pub fn into_payload(self) -> ArchivePathText {
        self.0
    }
}
#[rustfmt::skip]
impl From<ArchivePathText> for ArchivePath {
    fn from(payload: ArchivePathText) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MirrorAddressText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for MirrorAddressText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MirrorAddress {
    pub fn new(payload: MirrorAddressText) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MirrorAddressText {
        &self.0
    }
    pub fn into_payload(self) -> MirrorAddressText {
        self.0
    }
}
#[rustfmt::skip]
impl From<MirrorAddressText> for MirrorAddress {
    fn from(payload: MirrorAddressText) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CriomeSocketPathText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for CriomeSocketPathText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CriomeSocketPath {
    pub fn new(payload: CriomeSocketPathText) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CriomeSocketPathText {
        &self.0
    }
    pub fn into_payload(self) -> CriomeSocketPathText {
        self.0
    }
}
#[rustfmt::skip]
impl From<CriomeSocketPathText> for CriomeSocketPath {
    fn from(payload: CriomeSocketPathText) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GuardianPromptText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for GuardianPromptText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GuardianPrompt {
    pub fn new(payload: GuardianPromptText) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &GuardianPromptText {
        &self.0
    }
    pub fn into_payload(self) -> GuardianPromptText {
        self.0
    }
}
#[rustfmt::skip]
impl From<GuardianPromptText> for GuardianPrompt {
    fn from(payload: GuardianPromptText) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SelectedMirrorTarget {
    pub fn new(payload: Option<MirrorTarget>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<MirrorTarget> {
        &self.0
    }
    pub fn into_payload(self) -> Option<MirrorTarget> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<MirrorTarget>> for SelectedMirrorTarget {
    fn from(payload: Option<MirrorTarget>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SelectedCriomeGateTarget {
    pub fn new(payload: Option<CriomeGateTarget>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<CriomeGateTarget> {
        &self.0
    }
    pub fn into_payload(self) -> Option<CriomeGateTarget> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<CriomeGateTarget>> for SelectedCriomeGateTarget {
    fn from(payload: Option<CriomeGateTarget>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SelectedGuardianPromptTarget {
    pub fn new(payload: Option<GuardianPromptTarget>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<GuardianPromptTarget> {
        &self.0
    }
    pub fn into_payload(self) -> Option<GuardianPromptTarget> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<GuardianPromptTarget>> for SelectedGuardianPromptTarget {
    fn from(payload: Option<GuardianPromptTarget>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ImportedRecords {
    pub fn new(payload: Vec<ImportedRecord>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ImportedRecord> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ImportedRecord> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ImportedRecord>> for ImportedRecords {
    fn from(payload: Vec<ImportedRecord>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ImportRequest {
    pub fn new(payload: ImportedRecords) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ImportedRecords {
        &self.0
    }
    pub fn into_payload(self) -> ImportedRecords {
        self.0
    }
}
#[rustfmt::skip]
impl From<ImportedRecords> for ImportRequest {
    fn from(payload: ImportedRecords) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CollectRemovalCandidatesRequest {
    pub fn new(payload: RemovalCandidateCollection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RemovalCandidateCollection {
        &self.0
    }
    pub fn into_payload(self) -> RemovalCandidateCollection {
        self.0
    }
}
#[rustfmt::skip]
impl From<RemovalCandidateCollection> for CollectRemovalCandidatesRequest {
    fn from(payload: RemovalCandidateCollection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HeadDigestHex {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for HeadDigestHex {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SelectedHeadDigest {
    pub fn new(payload: Option<HeadDigestHex>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<HeadDigestHex> {
        &self.0
    }
    pub fn into_payload(self) -> Option<HeadDigestHex> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<HeadDigestHex>> for SelectedHeadDigest {
    fn from(payload: Option<HeadDigestHex>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HeadObjectHex {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for HeadObjectHex {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SelectedHeadObject {
    pub fn new(payload: Option<HeadObjectHex>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<HeadObjectHex> {
        &self.0
    }
    pub fn into_payload(self) -> Option<HeadObjectHex> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<HeadObjectHex>> for SelectedHeadObject {
    fn from(payload: Option<HeadObjectHex>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ArchiveDatabaseTarget {
    pub fn path(payload: ArchivePathText) -> Self {
        Self::Path(ArchivePath::new(payload))
    }
}

#[rustfmt::skip]
impl MirrorTarget {
    pub fn address(payload: MirrorAddressText) -> Self {
        Self::Address(MirrorAddress::new(payload))
    }
}

#[rustfmt::skip]
impl CriomeGateTarget {
    pub fn socket(payload: CriomeSocketPathText) -> Self {
        Self::Socket(CriomeSocketPath::new(payload))
    }
}

#[rustfmt::skip]
impl GuardianPromptTarget {
    pub fn prompt(payload: GuardianPromptText) -> Self {
        Self::Prompt(GuardianPrompt::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn configure(payload: ConfigureRequest) -> Self {
        Self::Configure(payload)
    }
    pub fn import(payload: ImportedRecords) -> Self {
        Self::Import(ImportRequest::new(payload))
    }
    pub fn collect_removal_candidates(payload: RemovalCandidateCollection) -> Self {
        Self::CollectRemovalCandidates(CollectRemovalCandidatesRequest::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn configured(payload: ConfigureReceipt) -> Self {
        Self::Configured(payload)
    }
    pub fn imported(payload: ImportReceipt) -> Self {
        Self::Imported(payload)
    }
    pub fn removal_candidates_collected(
        payload: RemovalCandidatesCollectedReceipt,
    ) -> Self {
        Self::RemovalCandidatesCollected(payload)
    }
    pub fn rejected(payload: ConfigureRejection) -> Self {
        Self::Rejected(payload)
    }
    pub fn head_observed(payload: VersionedLogHead) -> Self {
        Self::HeadObserved(payload)
    }
    pub fn head_object_observed(payload: VersionedLogHeadObject) -> Self {
        Self::HeadObjectObserved(payload)
    }
}

#[rustfmt::skip]
impl From<ArchivePath> for ArchiveDatabaseTarget {
    fn from(payload: ArchivePath) -> Self {
        Self::Path(payload)
    }
}

#[rustfmt::skip]
impl From<MirrorAddress> for MirrorTarget {
    fn from(payload: MirrorAddress) -> Self {
        Self::Address(payload)
    }
}

#[rustfmt::skip]
impl From<CriomeSocketPath> for CriomeGateTarget {
    fn from(payload: CriomeSocketPath) -> Self {
        Self::Socket(payload)
    }
}

#[rustfmt::skip]
impl From<GuardianPrompt> for GuardianPromptTarget {
    fn from(payload: GuardianPrompt) -> Self {
        Self::Prompt(payload)
    }
}

#[rustfmt::skip]
impl From<ConfigureRequest> for Input {
    fn from(payload: ConfigureRequest) -> Self {
        Self::Configure(payload)
    }
}

#[rustfmt::skip]
impl From<ImportRequest> for Input {
    fn from(payload: ImportRequest) -> Self {
        Self::Import(payload)
    }
}

#[rustfmt::skip]
impl From<CollectRemovalCandidatesRequest> for Input {
    fn from(payload: CollectRemovalCandidatesRequest) -> Self {
        Self::CollectRemovalCandidates(payload)
    }
}

#[rustfmt::skip]
impl From<ConfigureReceipt> for Output {
    fn from(payload: ConfigureReceipt) -> Self {
        Self::Configured(payload)
    }
}

#[rustfmt::skip]
impl From<ImportReceipt> for Output {
    fn from(payload: ImportReceipt) -> Self {
        Self::Imported(payload)
    }
}

#[rustfmt::skip]
impl From<RemovalCandidatesCollectedReceipt> for Output {
    fn from(payload: RemovalCandidatesCollectedReceipt) -> Self {
        Self::RemovalCandidatesCollected(payload)
    }
}

#[rustfmt::skip]
impl From<ConfigureRejection> for Output {
    fn from(payload: ConfigureRejection) -> Self {
        Self::Rejected(payload)
    }
}

#[rustfmt::skip]
impl From<VersionedLogHead> for Output {
    fn from(payload: VersionedLogHead) -> Self {
        Self::HeadObserved(payload)
    }
}

#[rustfmt::skip]
impl From<VersionedLogHeadObject> for Output {
    fn from(payload: VersionedLogHeadObject) -> Self {
        Self::HeadObjectObserved(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_CONFIGURE: u64 = 0x0000000100000002;
    pub const INPUT_IMPORT: u64 = 0x0001000100000002;
    pub const INPUT_COLLECT_REMOVAL_CANDIDATES: u64 = 0x0002000100000002;
    pub const INPUT_OBSERVE_HEAD: u64 = 0x0003000100000002;
    pub const INPUT_OBSERVE_HEAD_OBJECT: u64 = 0x0004000100000002;
    pub const OUTPUT_CONFIGURED: u64 = 0x0100000100000002;
    pub const OUTPUT_IMPORTED: u64 = 0x0101000100000002;
    pub const OUTPUT_REMOVAL_CANDIDATES_COLLECTED: u64 = 0x0102000100000002;
    pub const OUTPUT_REJECTED: u64 = 0x0103000100000002;
    pub const OUTPUT_HEAD_OBSERVED: u64 = 0x0104000100000002;
    pub const OUTPUT_HEAD_OBJECT_OBSERVED: u64 = 0x0105000100000002;
    pub const HANDSHAKE_REQUEST: u64 = 0xFF00000100000002;
    pub const HANDSHAKE_REPLY: u64 = 0xFF01000100000002;
    pub const ENGINE_REFUSAL: u64 = 0xFF02000100000002;
}

#[rustfmt::skip]
pub enum ContractMarker {}
#[rustfmt::skip]
impl signal_frame::WireContract for ContractMarker {
    const BINDING: signal_frame::ContractBinding = signal_frame::ContractBinding::new(
        match signal_frame::ContractId::try_new(2u32) {
            Ok(contract) => contract,
            Err(_) => panic!("generated contract ID must be nonzero"),
        },
        match signal_frame::WireRevision::try_new(1u16) {
            Ok(revision) => revision,
            Err(_) => panic!("generated wire revision must be nonzero"),
        },
    );
}
#[rustfmt::skip]
/// Why the daemon refused to produce an ordinary reply.
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq
)]
pub enum EngineRefusalReason {
    /// The engine ran and rejected the request with its typed
    /// domain error; the rendered error text is the detail.
    Rejected,
    /// The engine layer could not serve the request at all.
    Unavailable,
}
#[rustfmt::skip]
impl std::fmt::Display for EngineRefusalReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rejected => formatter.write_str("engine rejected the request"),
            Self::Unavailable => formatter.write_str("engine unavailable"),
        }
    }
}
#[rustfmt::skip]
/// The refusal reply a daemon writes when the engine failed, so
/// the caller receives a complete typed frame instead of a closed
/// socket it cannot distinguish from daemon death. The typed
/// engine error stays daemon-side; the wire carries the
/// classification plus the rendered error text.
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineRefusal {
    pub reason: EngineRefusalReason,
    pub detail: String,
}
#[rustfmt::skip]
impl EngineRefusal {
    pub fn rejected(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Rejected,
            detail,
        }
    }
    pub fn unavailable(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Unavailable,
            detail,
        }
    }
    pub fn encode_bound_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            signal_frame::SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&short_header::ENGINE_REFUSAL.to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    FrameEncode,
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    LegacyHeader { contract_id: u32, wire_revision: u16 },
    ContractMismatch { expected: u32, found: u32 },
    UnsupportedWireRevision { contract_id: u32, expected: u16, found: u16 },
    UnknownRoute { root: u8, variant: u8 },
    RouteBodyMismatch { root: u8, variant: u8, body: &'static str },
    UnexpectedFrameBody { found: &'static str },
    OperationCount { found: usize },
    EngineRefused { refusal: EngineRefusal },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::FrameEncode => {
                formatter.write_str("failed to encode bound signal frame")
            }
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::LegacyHeader { contract_id, wire_revision } => {
                write!(
                    formatter,
                    "legacy unbound signal frame ({contract_id}, {wire_revision})"
                )
            }
            Self::ContractMismatch { expected, found } => {
                write!(
                    formatter,
                    "signal contract mismatch: expected {expected}, found {found}"
                )
            }
            Self::UnsupportedWireRevision { contract_id, expected, found } => {
                write!(
                    formatter,
                    "unsupported wire revision for contract {contract_id}: expected {expected}, found {found}"
                )
            }
            Self::UnknownRoute { root, variant } => {
                write!(formatter, "unknown bound signal route ({root}, {variant})")
            }
            Self::RouteBodyMismatch { root, variant, body } => {
                write!(
                    formatter,
                    "bound signal route ({root}, {variant}) does not carry {body}"
                )
            }
            Self::UnexpectedFrameBody { found } => {
                write!(formatter, "expected one request frame, found {found}")
            }
            Self::OperationCount { found } => {
                write!(formatter, "expected one request operation, found {found}")
            }
            Self::EngineRefused { refusal } => {
                write!(formatter, "{}: {}", refusal.reason, refusal.detail)
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}
#[rustfmt::skip]
impl ContractMarker {
    pub fn handshake_request_frame(request: signal_frame::HandshakeRequest) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(0),
            ),
            FrameBody::HandshakeRequest(request),
        )
    }
    pub fn handshake_reply_frame(reply: signal_frame::HandshakeReply) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(1),
            ),
            FrameBody::HandshakeReply(reply),
        )
    }
    pub fn decode_frame(bytes: &[u8]) -> Result<Frame, SignalFrameError> {
        if bytes.len() < signal_frame::SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: bytes.len(),
            });
        }
        let mut header_bytes = [0_u8; signal_frame::SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&bytes[..signal_frame::SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let contract_id = header as u32;
        let wire_revision = (header >> 32) as u16;
        if contract_id == 0 || wire_revision == 0 {
            return Err(SignalFrameError::LegacyHeader {
                contract_id,
                wire_revision,
            });
        }
        if contract_id != 2u32 {
            return Err(SignalFrameError::ContractMismatch {
                expected: 2u32,
                found: contract_id,
            });
        }
        if wire_revision != 1u16 {
            return Err(SignalFrameError::UnsupportedWireRevision {
                contract_id,
                expected: 1u16,
                found: wire_revision,
            });
        }
        let root = (header >> 56) as u8;
        let variant = (header >> 48) as u8;
        match (root, variant) {
            (0, 0)
            | (0, 1)
            | (0, 2)
            | (0, 3)
            | (0, 4)
            | (1, 0)
            | (1, 1)
            | (1, 2)
            | (1, 3)
            | (1, 4)
            | (1, 5)
            | (0xff, 0)
            | (0xff, 1)
            | (0xff, 2) => {}
            _ => {
                return Err(SignalFrameError::UnknownRoute {
                    root,
                    variant,
                });
            }
        }
        if (root, variant) == (0xff, 2) {
            let refusal = rkyv::from_bytes::<
                EngineRefusal,
                rkyv::rancor::Error,
            >(&bytes[signal_frame::SHORT_HEADER_BYTE_COUNT..])
                .map_err(|_| SignalFrameError::ArchiveDecode)?;
            return Err(SignalFrameError::EngineRefused {
                refusal,
            });
        }
        let frame = Frame::decode(bytes).map_err(|_| SignalFrameError::ArchiveDecode)?;
        let header_route = signal_frame::WireRoute::new(
            signal_frame::RootCode::new(root),
            signal_frame::VariantCode::new(variant),
        );
        let body_matches = match frame.body() {
            FrameBody::HandshakeRequest(_) => (root, variant) == (0xff, 0),
            FrameBody::HandshakeReply(_) => (root, variant) == (0xff, 1),
            FrameBody::Request { request, .. } => {
                request.route().is_ok_and(|route| route == header_route)
            }
            FrameBody::Reply { reply, .. } => {
                match reply {
                    signal_frame::Reply::Accepted { per_operation, .. } => {
                        match per_operation.head() {
                            signal_frame::SubReply::Ok(output) => {
                                output.wire_route() == header_route
                            }
                            signal_frame::SubReply::Failed {
                                detail: Some(output),
                                ..
                            } => output.wire_route() == header_route,
                            signal_frame::SubReply::Invalidated
                            | signal_frame::SubReply::Failed { detail: None, .. }
                            | signal_frame::SubReply::Skipped => root == 1,
                        }
                    }
                    signal_frame::Reply::Rejected { .. } => root == 1,
                }
            }
        };
        if !body_matches {
            let body = match frame.body() {
                FrameBody::HandshakeRequest(_) => "handshake request",
                FrameBody::HandshakeReply(_) => "handshake reply",
                FrameBody::Request { .. } => "request",
                FrameBody::Reply { .. } => "reply",
            };
            return Err(SignalFrameError::RouteBodyMismatch {
                root,
                variant,
                body,
            });
        }
        Ok(frame)
    }
    pub fn decode_single_request(
        bytes: &[u8],
    ) -> Result<(signal_frame::ExchangeIdentifier, Input), SignalFrameError> {
        let frame = Self::decode_frame(bytes)?;
        match frame.into_body() {
            FrameBody::Request { exchange, request } => {
                let found = request.payloads().len();
                if found != 1 {
                    return Err(SignalFrameError::OperationCount {
                        found,
                    });
                }
                Ok((exchange, request.payloads.into_head()))
            }
            FrameBody::HandshakeRequest(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake request",
                })
            }
            FrameBody::HandshakeReply(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake reply",
                })
            }
            FrameBody::Reply { .. } => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "reply",
                })
            }
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Configure,
    Import,
    CollectRemovalCandidates,
    ObserveHead,
    ObserveHeadObject,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Configured,
    Imported,
    RemovalCandidatesCollected,
    Rejected,
    HeadObserved,
    HeadObjectObserved,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Configure(_) => InputRoute::Configure,
            Self::Import(_) => InputRoute::Import,
            Self::CollectRemovalCandidates(_) => InputRoute::CollectRemovalCandidates,
            Self::ObserveHead => InputRoute::ObserveHead,
            Self::ObserveHeadObject => InputRoute::ObserveHeadObject,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::Configure(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::Import(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::CollectRemovalCandidates(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(2),
                )
            }
            Self::ObserveHead => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(3),
                )
            }
            Self::ObserveHeadObject => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(4),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Configure(_) => short_header::INPUT_CONFIGURE,
            Self::Import(_) => short_header::INPUT_IMPORT,
            Self::CollectRemovalCandidates(_) => {
                short_header::INPUT_COLLECT_REMOVAL_CANDIDATES
            }
            Self::ObserveHead => short_header::INPUT_OBSERVE_HEAD,
            Self::ObserveHeadObject => short_header::INPUT_OBSERVE_HEAD_OBJECT,
        }
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Configured(_) => OutputRoute::Configured,
            Self::Imported(_) => OutputRoute::Imported,
            Self::RemovalCandidatesCollected(_) => {
                OutputRoute::RemovalCandidatesCollected
            }
            Self::Rejected(_) => OutputRoute::Rejected,
            Self::HeadObserved(_) => OutputRoute::HeadObserved,
            Self::HeadObjectObserved(_) => OutputRoute::HeadObjectObserved,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::Configured(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::Imported(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::RemovalCandidatesCollected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(2),
                )
            }
            Self::Rejected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(3),
                )
            }
            Self::HeadObserved(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(4),
                )
            }
            Self::HeadObjectObserved(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(5),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Configured(_) => short_header::OUTPUT_CONFIGURED,
            Self::Imported(_) => short_header::OUTPUT_IMPORTED,
            Self::RemovalCandidatesCollected(_) => {
                short_header::OUTPUT_REMOVAL_CANDIDATES_COLLECTED
            }
            Self::Rejected(_) => short_header::OUTPUT_REJECTED,
            Self::HeadObserved(_) => short_header::OUTPUT_HEAD_OBSERVED,
            Self::HeadObjectObserved(_) => short_header::OUTPUT_HEAD_OBJECT_OBSERVED,
        }
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Configure",
        "Import",
        "CollectRemovalCandidates",
        "ObserveHead",
        "ObserveHeadObject",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        let route = self.wire_route();
        u64::from(route.root().value()) | (u64::from(route.variant().value()) << 8)
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::BoundExchangeFrame<ContractMarker, Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let request = signal_frame::Request::from_payload(self);
        Frame::new(
            route,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
    pub fn encode_request_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_frame(exchange).encode().map_err(|_| SignalFrameError::FrameEncode)
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::new(
            route,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
    pub fn encode_reply_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_reply_frame(exchange)
            .encode()
            .map_err(|_| SignalFrameError::FrameEncode)
    }
}
